[meta title:"March Madness Viz" description:"An explanatory exploration of March Madness and what your chances are of creating a perfect backet for the NCAA Tournament." /]

[Header
  title:"Understanding March Madness"
  subtitle:"A visual exploration of what your chances are of creating a perfect March Madness backet for the NCAA Tournament."
  author:"Michelle Ho, Jon Alkan, and Austin Hutchinson" /]

[waypoint]
[aside]

[/aside]
## Overview of March Madness
Every year, college basketball teams compete to be one of the 64 teams that are invited to play for the NCAA National Championship in the March Madness tournament. As the largest 
NCAA basketball tournament, millions of fans flock to colleges around the nation to watch their favorite teams compete for the coveted title of National Champions. With such 
competition and chance as the tournament provides, gambling has become a large aspect of the tournament for fans. Every year, millions of fans place bets across all aspects of the 
tournament, the largest being the overall winner of the tournament. In order to get there, fans have developed a bracket gambling system. For each game in the tournament, fans can 
select which team they believe will win until they select a National Champion. 

With so many games, the payout is large and very hard to achieve with accuracy. But exactly how hard is it to correctly pick every winner in the tournament? It is so hard that it 
has never been done. There has never been a perfect bracket.
[/waypoint]

[waypoint]

## General Terminology
The March Madness NCAA Tournament consists of two tournaments, one for men and one for women. There are a total of 68 mens teams and 64 womens teams in their respective tournaments. 
For each tournament, the first 32 teams are selected based on their season records and divisional tournaments. The rest of the teams are selected by a commitee based off season 
performance, difficulty of schedule, and prior tournament outcomes. This selection commitee meets on the Sunday before the tournament begins, called Selection Sunday. The commitee 
also assigns each team a ranking (seed) and lays out the brackets for the tournament. 

The bracket is divided into 4 main sections denoting their geographical areas. The men's tournament starts with the two lowest seeded teams in each division playing to take the last 
seed in each division. After this, the 64 remaining teams play in "The Round of 64". After this, the winning teams play in "The Round of 32". The winning teams then proceed to "The 
Sweet Sixteen", then "The Elite 8", next "The Final Four", and finally "The National Championship" game.
[/waypoint]

[aside]
[data name:"elite" source:"elite8.csv" /]

[TeamHistory data:elite /]


[/aside]

## Jon's Section to Fill In
Jon's section to fill in
[var name:"radioVal" value:"Sweet16" /]
[Radio value:radioVal options:`["Sweet16", "Elite8", "Final4", "NatApp", "NatWins"]`  /]


[waypoint]
## Bracket Madness
Every year 68 teams enter the March Madness Bracket...Your odds of getting a perfect bracket? Try **1 in 9,223,372,036,854,775,808 or 1 in 9.2 quintillion.** (This excludes the first 
four games as a 16 seed has never beaten a 1 seed.) To put this into perspective, you have a better chance of:
* Winning an Academy Award (1 in ~11,500)
* Getting Struck by Lightning (1 in ~700,000)
* Becoming President (1 in ~10,000,000)
* Winning the Lottery (1 in ~175,223,510)
[/waypoint]

[waypoint]
[aside]
[CustomD3Component state:selectVal /]
[var name:"selectVal" value:"2" /]
Number of Teams: [Select value:selectVal options:`["2", "4"]`  /]
[/aside]

## Where does 1 in 9.2 quintillion come from?
To understand where these odds come from, it's important to understand probability. [link text:"Probability" href:"https://en.wikipedia.org/wiki/Probability" /] is the extent
to which something is probable, or in simpler terms, the likelihood of something happening or being the case.

Let's start small scale.
Let's assume we have 2 teams, and 1 game being played. If there are two teams, assuming teams are equal in skill and all other things held constant, each team will have a 50% chance 
or 1/2 probability of winning the match.

If we have 4 teams, with 3 games being played, assuming teams are equal in skill and all other things held constant, each team will have a 1/8 probability of winning.
[/waypoint]

[waypoint]
[aside]
// [data name:"bracket" source:"bracket.json" /]
// [TeamHistory data:bracket /]
[/aside]

## Where do these numbers come from?
The probabilities above assume that all teams in the tournament are equal and thus have an equal probability of winning a match. That is, with this reasoning, we assume that Duke University
and Washington State University are equal matches (when they are very much not). For the purpose of understanding probability, we will hold this assumption.

We can use the equation to understand this further:
[Equation]
  f(n) = (1/2)^n
[/Equation]
The probability of getting a perfect bracket is dependent on n, the number of teams there are in the bracket. 

[/waypoint]


[waypoint]

## What are the odds based off ranking?
[aside]
[data name:"simpleodds" source:"simpleOddsJSON.json" /]
[var name:"seedSelect" value:1 /]

Selected Team Seed: [Display value:seedSelect /]
[IdyllVegaLite data:`simpleodds.slice(seedSelect-1, seedSelect)` spec:`{
     width: 500,
     height: 100,
       "layer": [{
            "mark": "bar",
            "encoding": {
                x: {
                      field: "p_win",
                      type: "quantitative",
                      axis: {title: "Chance of Winning (Percent)"},
                      stack: "normalize",
                      scale: { domain: [0, 100] }
                },
           }
        }, {
           "mark": {
            "type": "text",
            "align": "left",
            "baseline": "middle",
            "dx": 3
        },
        "encoding": {
            x: {
                   field: "p_win",
                   type: "quantitative",
                   axis: {title: "Chance of Winning (Percent)"},
                   stack: "normalize",
                   scale: { domain: [0, 100] }
            },
            "text": {"field": "p_win", "type": "quantitative"},
          }
        }]
}` /]

[/aside]
We can make this more realistic. If we neglect the assumption that all teams are equal, we can start to understand how teams will actually fare in the tournament to make a better prediction
of who will win.

In the tournament, each team is given a ranking that depends on their play throughout the year leading up to the tournament. Within each of the four divions, teams are ranked 1 through 16 and
 from these numbers their first games are decided. The games are decided so that, initially, the #1 ranked (seeded) team plays the #16 seed team, the #2 seed plays #15, #3 seed plays #14 seed,
  and so on. Historically, these teams have a set percentage of winning the first round based off these ranks. The visualization to the right shows the likelihood of each team winning their 
  first game based off their rank.

Select Team Seed: 
1 [Range value:seedSelect min:1 max:16 /] 16

[/waypoint]
